name: Deploy to GitHub Pages

permissions:
  id-token: write
  
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Publish .NET Core Project
      run: dotnet publish BGE2/Server/BGE2.Server.csproj -c Release -o release --nologo

    - name: Commit wwwroot to GitHub Pages
      uses: actions/deploy-pages@v1.2.4
      with:
        token: ${{ github.token }}
        artifact_name: release
