name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.103
      
      - name: Publish .NET Core Project
        run: |
          cd Server
          dotnet build --configuration Release --no-restore
          dotnet publish BGE2.Server.csproj -c Release -o release --nologo
      
      - name: Commit wwwroot to GitHub Pages
        uses: avinal/github-pages-deploy-action@v0.9
        with:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
      
